// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/carpool (interfaces: CarpoolService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . CarpoolService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCarpoolService is a mock of CarpoolService interface.
type MockCarpoolService struct {
	ctrl     *gomock.Controller
	recorder *MockCarpoolServiceMockRecorder
	isgomock struct{}
}

// MockCarpoolServiceMockRecorder is the mock recorder for MockCarpoolService.
type MockCarpoolServiceMockRecorder struct {
	mock *MockCarpoolService
}

// NewMockCarpoolService creates a new mock instance.
func NewMockCarpoolService(ctrl *gomock.Controller) *MockCarpoolService {
	mock := &MockCarpoolService{ctrl: ctrl}
	mock.recorder = &MockCarpoolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarpoolService) EXPECT() *MockCarpoolServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCarpoolService) Create(ctx context.Context, eventID, driverID uuid.UUID, req model.CreateCarpoolRequest) (model.Carpool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, driverID, req)
	ret0, _ := ret[0].(model.Carpool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCarpoolServiceMockRecorder) Create(ctx, eventID, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCarpoolService)(nil).Create), ctx, eventID, driverID, req)
}

// Join mocks base method.
func (m *MockCarpoolService) Join(ctx context.Context, eventID, carpoolID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, eventID, carpoolID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockCarpoolServiceMockRecorder) Join(ctx, eventID, carpoolID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockCarpoolService)(nil).Join), ctx, eventID, carpoolID, userID)
}

// List mocks base method.
func (m *MockCarpoolService) List(ctx context.Context, eventID, userID uuid.UUID) ([]model.Carpool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, userID)
	ret0, _ := ret[0].([]model.Carpool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCarpoolServiceMockRecorder) List(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCarpoolService)(nil).List), ctx, eventID, userID)
}
