// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/collection (interfaces: CollectionRepo,EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . CollectionRepo,EventRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionRepo is a mock of CollectionRepo interface.
type MockCollectionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionRepoMockRecorder
	isgomock struct{}
}

// MockCollectionRepoMockRecorder is the mock recorder for MockCollectionRepo.
type MockCollectionRepoMockRecorder struct {
	mock *MockCollectionRepo
}

// NewMockCollectionRepo creates a new mock instance.
func NewMockCollectionRepo(ctrl *gomock.Controller) *MockCollectionRepo {
	mock := &MockCollectionRepo{ctrl: ctrl}
	mock.recorder = &MockCollectionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionRepo) EXPECT() *MockCollectionRepoMockRecorder {
	return m.recorder
}

// CountPaidContributions mocks base method.
func (m *MockCollectionRepo) CountPaidContributions(ctx context.Context, collectionID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPaidContributions", ctx, collectionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPaidContributions indicates an expected call of CountPaidContributions.
func (mr *MockCollectionRepoMockRecorder) CountPaidContributions(ctx, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPaidContributions", reflect.TypeOf((*MockCollectionRepo)(nil).CountPaidContributions), ctx, collectionID)
}

// Create mocks base method.
func (m *MockCollectionRepo) Create(ctx context.Context, eventID uuid.UUID, req model.CreateCollectionRequest, createdBy uuid.UUID) (model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, req, createdBy)
	ret0, _ := ret[0].(model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCollectionRepoMockRecorder) Create(ctx, eventID, req, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionRepo)(nil).Create), ctx, eventID, req, createdBy)
}

// Delete mocks base method.
func (m *MockCollectionRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCollectionRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCollectionRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCollectionRepo)(nil).GetByID), ctx, id)
}

// ListByEvent mocks base method.
func (m *MockCollectionRepo) ListByEvent(ctx context.Context, eventID uuid.UUID) ([]model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", ctx, eventID)
	ret0, _ := ret[0].([]model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockCollectionRepoMockRecorder) ListByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockCollectionRepo)(nil).ListByEvent), ctx, eventID)
}

// ToggleContribution mocks base method.
func (m *MockCollectionRepo) ToggleContribution(ctx context.Context, collectionID, userID uuid.UUID) (model.CollectionContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleContribution", ctx, collectionID, userID)
	ret0, _ := ret[0].(model.CollectionContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleContribution indicates an expected call of ToggleContribution.
func (mr *MockCollectionRepoMockRecorder) ToggleContribution(ctx, collectionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleContribution", reflect.TypeOf((*MockCollectionRepo)(nil).ToggleContribution), ctx, collectionID, userID)
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// CountConfirmedParticipants mocks base method.
func (m *MockEventRepo) CountConfirmedParticipants(ctx context.Context, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfirmedParticipants", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfirmedParticipants indicates an expected call of CountConfirmedParticipants.
func (mr *MockEventRepoMockRecorder) CountConfirmedParticipants(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfirmedParticipants", reflect.TypeOf((*MockEventRepo)(nil).CountConfirmedParticipants), ctx, eventID)
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// IsConfirmedParticipant mocks base method.
func (m *MockEventRepo) IsConfirmedParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmedParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmedParticipant indicates an expected call of IsConfirmedParticipant.
func (mr *MockEventRepoMockRecorder) IsConfirmedParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmedParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsConfirmedParticipant), ctx, eventID, userID)
}

// IsParticipant mocks base method.
func (m *MockEventRepo) IsParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockEventRepoMockRecorder) IsParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsParticipant), ctx, eventID, userID)
}
