// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/item (interfaces: ItemRepo,EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . ItemRepo,EventRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockItemRepo is a mock of ItemRepo interface.
type MockItemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockItemRepoMockRecorder
	isgomock struct{}
}

// MockItemRepoMockRecorder is the mock recorder for MockItemRepo.
type MockItemRepoMockRecorder struct {
	mock *MockItemRepo
}

// NewMockItemRepo creates a new mock instance.
func NewMockItemRepo(ctrl *gomock.Controller) *MockItemRepo {
	mock := &MockItemRepo{ctrl: ctrl}
	mock.recorder = &MockItemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemRepo) EXPECT() *MockItemRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockItemRepo) Create(ctx context.Context, eventID uuid.UUID, req model.CreateItemRequest) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, req)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockItemRepoMockRecorder) Create(ctx, eventID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockItemRepo)(nil).Create), ctx, eventID, req)
}

// GetByID mocks base method.
func (m *MockItemRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockItemRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockItemRepo)(nil).GetByID), ctx, id)
}

// ListByEvent mocks base method.
func (m *MockItemRepo) ListByEvent(ctx context.Context, eventID uuid.UUID) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", ctx, eventID)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockItemRepoMockRecorder) ListByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockItemRepo)(nil).ListByEvent), ctx, eventID)
}

// UpdateAssignment mocks base method.
func (m *MockItemRepo) UpdateAssignment(ctx context.Context, id uuid.UUID, assignedTo *uuid.UUID) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssignment", ctx, id, assignedTo)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAssignment indicates an expected call of UpdateAssignment.
func (mr *MockItemRepoMockRecorder) UpdateAssignment(ctx, id, assignedTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssignment", reflect.TypeOf((*MockItemRepo)(nil).UpdateAssignment), ctx, id, assignedTo)
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// IsConfirmedParticipant mocks base method.
func (m *MockEventRepo) IsConfirmedParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmedParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmedParticipant indicates an expected call of IsConfirmedParticipant.
func (mr *MockEventRepoMockRecorder) IsConfirmedParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmedParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsConfirmedParticipant), ctx, eventID, userID)
}

// IsParticipant mocks base method.
func (m *MockEventRepo) IsParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockEventRepoMockRecorder) IsParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsParticipant), ctx, eventID, userID)
}
