// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/event (interfaces: EventRepo,UserRepo,NotificationRepo,Mailer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . EventRepo,UserRepo,NotificationRepo,Mailer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// AddChangeLog mocks base method.
func (m *MockEventRepo) AddChangeLog(ctx context.Context, eventID, changedBy uuid.UUID, field, oldVal, newVal string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChangeLog", ctx, eventID, changedBy, field, oldVal, newVal)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChangeLog indicates an expected call of AddChangeLog.
func (mr *MockEventRepoMockRecorder) AddChangeLog(ctx, eventID, changedBy, field, oldVal, newVal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChangeLog", reflect.TypeOf((*MockEventRepo)(nil).AddChangeLog), ctx, eventID, changedBy, field, oldVal, newVal)
}

// AddParticipant mocks base method.
func (m *MockEventRepo) AddParticipant(ctx context.Context, eventID, userID uuid.UUID, status string) (model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, eventID, userID, status)
	ret0, _ := ret[0].(model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockEventRepoMockRecorder) AddParticipant(ctx, eventID, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockEventRepo)(nil).AddParticipant), ctx, eventID, userID, status)
}

// Create mocks base method.
func (m *MockEventRepo) Create(ctx context.Context, req model.CreateEventRequest, organizerID uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, organizerID)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventRepoMockRecorder) Create(ctx, req, organizerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepo)(nil).Create), ctx, req, organizerID)
}

// Delete mocks base method.
func (m *MockEventRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// GetByInviteToken mocks base method.
func (m *MockEventRepo) GetByInviteToken(ctx context.Context, token uuid.UUID) (model.InviteEventInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteToken", ctx, token)
	ret0, _ := ret[0].(model.InviteEventInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteToken indicates an expected call of GetByInviteToken.
func (mr *MockEventRepoMockRecorder) GetByInviteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteToken", reflect.TypeOf((*MockEventRepo)(nil).GetByInviteToken), ctx, token)
}

// GetDetail mocks base method.
func (m *MockEventRepo) GetDetail(ctx context.Context, eventID, userID uuid.UUID) (model.EventDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, eventID, userID)
	ret0, _ := ret[0].(model.EventDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockEventRepoMockRecorder) GetDetail(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockEventRepo)(nil).GetDetail), ctx, eventID, userID)
}

// ListForUserEnriched mocks base method.
func (m *MockEventRepo) ListForUserEnriched(ctx context.Context, userID uuid.UUID) ([]model.EventListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUserEnriched", ctx, userID)
	ret0, _ := ret[0].([]model.EventListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUserEnriched indicates an expected call of ListForUserEnriched.
func (mr *MockEventRepoMockRecorder) ListForUserEnriched(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUserEnriched", reflect.TypeOf((*MockEventRepo)(nil).ListForUserEnriched), ctx, userID)
}

// ListParticipants mocks base method.
func (m *MockEventRepo) ListParticipants(ctx context.Context, eventID uuid.UUID) ([]model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", ctx, eventID)
	ret0, _ := ret[0].([]model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockEventRepoMockRecorder) ListParticipants(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockEventRepo)(nil).ListParticipants), ctx, eventID)
}

// Update mocks base method.
func (m *MockEventRepo) Update(ctx context.Context, id uuid.UUID, req model.UpdateEventRequest) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEventRepoMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventRepo)(nil).Update), ctx, id, req)
}

// UpdateParticipantStatus mocks base method.
func (m *MockEventRepo) UpdateParticipantStatus(ctx context.Context, eventID, userID uuid.UUID, status string) (model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantStatus", ctx, eventID, userID, status)
	ret0, _ := ret[0].(model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipantStatus indicates an expected call of UpdateParticipantStatus.
func (mr *MockEventRepoMockRecorder) UpdateParticipantStatus(ctx, eventID, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantStatus", reflect.TypeOf((*MockEventRepo)(nil).UpdateParticipantStatus), ctx, eventID, userID, status)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id uuid.UUID) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationRepo) Create(ctx context.Context, userID uuid.UUID, eventID *uuid.UUID, notifType, message string) (model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, eventID, notifType, message)
	ret0, _ := ret[0].(model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepoMockRecorder) Create(ctx, userID, eventID, notifType, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepo)(nil).Create), ctx, userID, eventID, notifType, message)
}

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendInvite mocks base method.
func (m *MockMailer) SendInvite(toEmail, eventTitle, organizerName, inviteToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvite", toEmail, eventTitle, organizerName, inviteToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvite indicates an expected call of SendInvite.
func (mr *MockMailerMockRecorder) SendInvite(toEmail, eventTitle, organizerName, inviteToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvite", reflect.TypeOf((*MockMailer)(nil).SendInvite), toEmail, eventTitle, organizerName, inviteToken)
}
