// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/notification (interfaces: NotificationService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . NotificationService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockNotificationService) List(ctx context.Context, userID uuid.UUID) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationServiceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationService)(nil).List), ctx, userID)
}

// MarkRead mocks base method.
func (m *MockNotificationService) MarkRead(ctx context.Context, notifID, userID uuid.UUID) (model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, notifID, userID)
	ret0, _ := ret[0].(model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotificationServiceMockRecorder) MarkRead(ctx, notifID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotificationService)(nil).MarkRead), ctx, notifID, userID)
}
