ALTER TABLE users
    ADD COLUMN IF NOT EXISTS last_name  TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS birth_date DATE,
    ADD COLUMN IF NOT EXISTS city       TEXT    NOT NULL DEFAULT '';
