// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/poll (interfaces: PollService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . PollService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPollService is a mock of PollService interface.
type MockPollService struct {
	ctrl     *gomock.Controller
	recorder *MockPollServiceMockRecorder
	isgomock struct{}
}

// MockPollServiceMockRecorder is the mock recorder for MockPollService.
type MockPollServiceMockRecorder struct {
	mock *MockPollService
}

// NewMockPollService creates a new mock instance.
func NewMockPollService(ctrl *gomock.Controller) *MockPollService {
	mock := &MockPollService{ctrl: ctrl}
	mock.recorder = &MockPollServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollService) EXPECT() *MockPollServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPollService) Create(ctx context.Context, eventID, userID uuid.UUID, req model.CreatePollRequest) (model.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, userID, req)
	ret0, _ := ret[0].(model.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPollServiceMockRecorder) Create(ctx, eventID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPollService)(nil).Create), ctx, eventID, userID, req)
}

// List mocks base method.
func (m *MockPollService) List(ctx context.Context, eventID, userID uuid.UUID) ([]model.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, userID)
	ret0, _ := ret[0].([]model.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPollServiceMockRecorder) List(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPollService)(nil).List), ctx, eventID, userID)
}

// Vote mocks base method.
func (m *MockPollService) Vote(ctx context.Context, eventID, pollID, userID uuid.UUID, req model.VoteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", ctx, eventID, pollID, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vote indicates an expected call of Vote.
func (mr *MockPollServiceMockRecorder) Vote(ctx, eventID, pollID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockPollService)(nil).Vote), ctx, eventID, pollID, userID, req)
}
