// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/item (interfaces: ItemService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . ItemService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockItemService is a mock of ItemService interface.
type MockItemService struct {
	ctrl     *gomock.Controller
	recorder *MockItemServiceMockRecorder
	isgomock struct{}
}

// MockItemServiceMockRecorder is the mock recorder for MockItemService.
type MockItemServiceMockRecorder struct {
	mock *MockItemService
}

// NewMockItemService creates a new mock instance.
func NewMockItemService(ctrl *gomock.Controller) *MockItemService {
	mock := &MockItemService{ctrl: ctrl}
	mock.recorder = &MockItemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemService) EXPECT() *MockItemServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockItemService) Create(ctx context.Context, eventID, userID uuid.UUID, req model.CreateItemRequest) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, userID, req)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockItemServiceMockRecorder) Create(ctx, eventID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockItemService)(nil).Create), ctx, eventID, userID, req)
}

// List mocks base method.
func (m *MockItemService) List(ctx context.Context, eventID, userID uuid.UUID) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, userID)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockItemServiceMockRecorder) List(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockItemService)(nil).List), ctx, eventID, userID)
}

// UpdateAssignment mocks base method.
func (m *MockItemService) UpdateAssignment(ctx context.Context, eventID, itemID, userID uuid.UUID, req model.UpdateItemRequest) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssignment", ctx, eventID, itemID, userID, req)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAssignment indicates an expected call of UpdateAssignment.
func (mr *MockItemServiceMockRecorder) UpdateAssignment(ctx, eventID, itemID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssignment", reflect.TypeOf((*MockItemService)(nil).UpdateAssignment), ctx, eventID, itemID, userID, req)
}
