// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/eventlink (interfaces: EventLinkRepo,EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . EventLinkRepo,EventRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventLinkRepo is a mock of EventLinkRepo interface.
type MockEventLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventLinkRepoMockRecorder
	isgomock struct{}
}

// MockEventLinkRepoMockRecorder is the mock recorder for MockEventLinkRepo.
type MockEventLinkRepoMockRecorder struct {
	mock *MockEventLinkRepo
}

// NewMockEventLinkRepo creates a new mock instance.
func NewMockEventLinkRepo(ctrl *gomock.Controller) *MockEventLinkRepo {
	mock := &MockEventLinkRepo{ctrl: ctrl}
	mock.recorder = &MockEventLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLinkRepo) EXPECT() *MockEventLinkRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventLinkRepo) Create(ctx context.Context, eventID, userID uuid.UUID, req model.CreateEventLinkRequest) (model.EventLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, userID, req)
	ret0, _ := ret[0].(model.EventLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventLinkRepoMockRecorder) Create(ctx, eventID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventLinkRepo)(nil).Create), ctx, eventID, userID, req)
}

// Delete mocks base method.
func (m *MockEventLinkRepo) Delete(ctx context.Context, linkID, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, linkID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventLinkRepoMockRecorder) Delete(ctx, linkID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventLinkRepo)(nil).Delete), ctx, linkID, eventID)
}

// List mocks base method.
func (m *MockEventLinkRepo) List(ctx context.Context, eventID uuid.UUID) ([]model.EventLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID)
	ret0, _ := ret[0].([]model.EventLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventLinkRepoMockRecorder) List(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventLinkRepo)(nil).List), ctx, eventID)
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// IsParticipant mocks base method.
func (m *MockEventRepo) IsParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockEventRepoMockRecorder) IsParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsParticipant), ctx, eventID, userID)
}
