// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/eventlink (interfaces: EventLinkService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . EventLinkService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventLinkService is a mock of EventLinkService interface.
type MockEventLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockEventLinkServiceMockRecorder
	isgomock struct{}
}

// MockEventLinkServiceMockRecorder is the mock recorder for MockEventLinkService.
type MockEventLinkServiceMockRecorder struct {
	mock *MockEventLinkService
}

// NewMockEventLinkService creates a new mock instance.
func NewMockEventLinkService(ctrl *gomock.Controller) *MockEventLinkService {
	mock := &MockEventLinkService{ctrl: ctrl}
	mock.recorder = &MockEventLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLinkService) EXPECT() *MockEventLinkServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventLinkService) Create(ctx context.Context, eventID, userID uuid.UUID, req model.CreateEventLinkRequest) (model.EventLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, userID, req)
	ret0, _ := ret[0].(model.EventLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventLinkServiceMockRecorder) Create(ctx, eventID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventLinkService)(nil).Create), ctx, eventID, userID, req)
}

// Delete mocks base method.
func (m *MockEventLinkService) Delete(ctx context.Context, eventID, linkID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID, linkID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventLinkServiceMockRecorder) Delete(ctx, eventID, linkID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventLinkService)(nil).Delete), ctx, eventID, linkID, userID)
}

// List mocks base method.
func (m *MockEventLinkService) List(ctx context.Context, eventID, userID uuid.UUID) ([]model.EventLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, userID)
	ret0, _ := ret[0].([]model.EventLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventLinkServiceMockRecorder) List(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventLinkService)(nil).List), ctx, eventID, userID)
}
