// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/event (interfaces: EventService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . EventService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventService) Create(ctx context.Context, req model.CreateEventRequest, organizerID uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, organizerID)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventServiceMockRecorder) Create(ctx, req, organizerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventService)(nil).Create), ctx, req, organizerID)
}

// Delete mocks base method.
func (m *MockEventService) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventServiceMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventService)(nil).Delete), ctx, id, userID)
}

// GetByID mocks base method.
func (m *MockEventService) GetByID(ctx context.Context, id, userID uuid.UUID) (model.EventDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(model.EventDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventServiceMockRecorder) GetByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventService)(nil).GetByID), ctx, id, userID)
}

// GetByInviteToken mocks base method.
func (m *MockEventService) GetByInviteToken(ctx context.Context, token uuid.UUID) (model.InviteEventInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteToken", ctx, token)
	ret0, _ := ret[0].(model.InviteEventInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteToken indicates an expected call of GetByInviteToken.
func (mr *MockEventServiceMockRecorder) GetByInviteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteToken", reflect.TypeOf((*MockEventService)(nil).GetByInviteToken), ctx, token)
}

// InviteParticipant mocks base method.
func (m *MockEventService) InviteParticipant(ctx context.Context, eventID, organizerID uuid.UUID, req model.InviteParticipantRequest) (model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteParticipant", ctx, eventID, organizerID, req)
	ret0, _ := ret[0].(model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteParticipant indicates an expected call of InviteParticipant.
func (mr *MockEventServiceMockRecorder) InviteParticipant(ctx, eventID, organizerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteParticipant", reflect.TypeOf((*MockEventService)(nil).InviteParticipant), ctx, eventID, organizerID, req)
}

// JoinByInviteToken mocks base method.
func (m *MockEventService) JoinByInviteToken(ctx context.Context, token, userID uuid.UUID, req model.JoinByInviteTokenRequest) (model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinByInviteToken", ctx, token, userID, req)
	ret0, _ := ret[0].(model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinByInviteToken indicates an expected call of JoinByInviteToken.
func (mr *MockEventServiceMockRecorder) JoinByInviteToken(ctx, token, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinByInviteToken", reflect.TypeOf((*MockEventService)(nil).JoinByInviteToken), ctx, token, userID, req)
}

// List mocks base method.
func (m *MockEventService) List(ctx context.Context, userID uuid.UUID) ([]model.EventListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]model.EventListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventServiceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventService)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockEventService) Update(ctx context.Context, id, userID uuid.UUID, req model.UpdateEventRequest) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, req)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEventServiceMockRecorder) Update(ctx, id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventService)(nil).Update), ctx, id, userID, req)
}

// UpdateParticipantStatus mocks base method.
func (m *MockEventService) UpdateParticipantStatus(ctx context.Context, eventID, targetUserID, callerID uuid.UUID, req model.UpdateParticipantStatusRequest) (model.EventParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantStatus", ctx, eventID, targetUserID, callerID, req)
	ret0, _ := ret[0].(model.EventParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipantStatus indicates an expected call of UpdateParticipantStatus.
func (mr *MockEventServiceMockRecorder) UpdateParticipantStatus(ctx, eventID, targetUserID, callerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantStatus", reflect.TypeOf((*MockEventService)(nil).UpdateParticipantStatus), ctx, eventID, targetUserID, callerID, req)
}
