// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/handler/collection (interfaces: CollectionService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . CollectionService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionService is a mock of CollectionService interface.
type MockCollectionService struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionServiceMockRecorder
	isgomock struct{}
}

// MockCollectionServiceMockRecorder is the mock recorder for MockCollectionService.
type MockCollectionServiceMockRecorder struct {
	mock *MockCollectionService
}

// NewMockCollectionService creates a new mock instance.
func NewMockCollectionService(ctrl *gomock.Controller) *MockCollectionService {
	mock := &MockCollectionService{ctrl: ctrl}
	mock.recorder = &MockCollectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionService) EXPECT() *MockCollectionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCollectionService) Create(ctx context.Context, eventID, userID uuid.UUID, req model.CreateCollectionRequest) (model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, userID, req)
	ret0, _ := ret[0].(model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCollectionServiceMockRecorder) Create(ctx, eventID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionService)(nil).Create), ctx, eventID, userID, req)
}

// Delete mocks base method.
func (m *MockCollectionService) Delete(ctx context.Context, eventID, collectionID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID, collectionID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionServiceMockRecorder) Delete(ctx, eventID, collectionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionService)(nil).Delete), ctx, eventID, collectionID, userID)
}

// List mocks base method.
func (m *MockCollectionService) List(ctx context.Context, eventID, userID uuid.UUID) ([]model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, userID)
	ret0, _ := ret[0].([]model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCollectionServiceMockRecorder) List(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCollectionService)(nil).List), ctx, eventID, userID)
}

// Summary mocks base method.
func (m *MockCollectionService) Summary(ctx context.Context, eventID, userID uuid.UUID) (model.EventCollectionsSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, eventID, userID)
	ret0, _ := ret[0].(model.EventCollectionsSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockCollectionServiceMockRecorder) Summary(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockCollectionService)(nil).Summary), ctx, eventID, userID)
}

// ToggleContribution mocks base method.
func (m *MockCollectionService) ToggleContribution(ctx context.Context, eventID, collectionID, userID uuid.UUID) (model.CollectionContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleContribution", ctx, eventID, collectionID, userID)
	ret0, _ := ret[0].(model.CollectionContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleContribution indicates an expected call of ToggleContribution.
func (mr *MockCollectionServiceMockRecorder) ToggleContribution(ctx, eventID, collectionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleContribution", reflect.TypeOf((*MockCollectionService)(nil).ToggleContribution), ctx, eventID, collectionID, userID)
}
