// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/notification (interfaces: NotificationRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . NotificationRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockNotificationRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationRepo)(nil).GetByID), ctx, id)
}

// ListForUser mocks base method.
func (m *MockNotificationRepo) ListForUser(ctx context.Context, userID uuid.UUID) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockNotificationRepoMockRecorder) ListForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockNotificationRepo)(nil).ListForUser), ctx, userID)
}

// MarkRead mocks base method.
func (m *MockNotificationRepo) MarkRead(ctx context.Context, id uuid.UUID) (model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, id)
	ret0, _ := ret[0].(model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotificationRepoMockRecorder) MarkRead(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkRead), ctx, id)
}
