// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/poll (interfaces: PollRepo,EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . PollRepo,EventRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPollRepo is a mock of PollRepo interface.
type MockPollRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPollRepoMockRecorder
	isgomock struct{}
}

// MockPollRepoMockRecorder is the mock recorder for MockPollRepo.
type MockPollRepoMockRecorder struct {
	mock *MockPollRepo
}

// NewMockPollRepo creates a new mock instance.
func NewMockPollRepo(ctrl *gomock.Controller) *MockPollRepo {
	mock := &MockPollRepo{ctrl: ctrl}
	mock.recorder = &MockPollRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollRepo) EXPECT() *MockPollRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPollRepo) Create(ctx context.Context, eventID uuid.UUID, req model.CreatePollRequest, createdBy uuid.UUID) (model.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, req, createdBy)
	ret0, _ := ret[0].(model.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPollRepoMockRecorder) Create(ctx, eventID, req, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPollRepo)(nil).Create), ctx, eventID, req, createdBy)
}

// GetByID mocks base method.
func (m *MockPollRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPollRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPollRepo)(nil).GetByID), ctx, id)
}

// GetOption mocks base method.
func (m *MockPollRepo) GetOption(ctx context.Context, optionID uuid.UUID) (model.PollOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOption", ctx, optionID)
	ret0, _ := ret[0].(model.PollOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOption indicates an expected call of GetOption.
func (mr *MockPollRepoMockRecorder) GetOption(ctx, optionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOption", reflect.TypeOf((*MockPollRepo)(nil).GetOption), ctx, optionID)
}

// ListByEvent mocks base method.
func (m *MockPollRepo) ListByEvent(ctx context.Context, eventID uuid.UUID) ([]model.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", ctx, eventID)
	ret0, _ := ret[0].([]model.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockPollRepoMockRecorder) ListByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockPollRepo)(nil).ListByEvent), ctx, eventID)
}

// Vote mocks base method.
func (m *MockPollRepo) Vote(ctx context.Context, optionID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", ctx, optionID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vote indicates an expected call of Vote.
func (mr *MockPollRepoMockRecorder) Vote(ctx, optionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockPollRepo)(nil).Vote), ctx, optionID, userID)
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// IsConfirmedParticipant mocks base method.
func (m *MockEventRepo) IsConfirmedParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmedParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmedParticipant indicates an expected call of IsConfirmedParticipant.
func (mr *MockEventRepoMockRecorder) IsConfirmedParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmedParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsConfirmedParticipant), ctx, eventID, userID)
}

// IsParticipant mocks base method.
func (m *MockEventRepo) IsParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockEventRepoMockRecorder) IsParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsParticipant), ctx, eventID, userID)
}
