// Code generated by MockGen. DO NOT EDIT.
// Source: bimeet/internal/service/carpool (interfaces: CarpoolRepo,EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock.go -package=mock . CarpoolRepo,EventRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "bimeet/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCarpoolRepo is a mock of CarpoolRepo interface.
type MockCarpoolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCarpoolRepoMockRecorder
	isgomock struct{}
}

// MockCarpoolRepoMockRecorder is the mock recorder for MockCarpoolRepo.
type MockCarpoolRepoMockRecorder struct {
	mock *MockCarpoolRepo
}

// NewMockCarpoolRepo creates a new mock instance.
func NewMockCarpoolRepo(ctrl *gomock.Controller) *MockCarpoolRepo {
	mock := &MockCarpoolRepo{ctrl: ctrl}
	mock.recorder = &MockCarpoolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarpoolRepo) EXPECT() *MockCarpoolRepoMockRecorder {
	return m.recorder
}

// AddPassenger mocks base method.
func (m *MockCarpoolRepo) AddPassenger(ctx context.Context, carpoolID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPassenger", ctx, carpoolID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPassenger indicates an expected call of AddPassenger.
func (mr *MockCarpoolRepoMockRecorder) AddPassenger(ctx, carpoolID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPassenger", reflect.TypeOf((*MockCarpoolRepo)(nil).AddPassenger), ctx, carpoolID, userID)
}

// CountPassengers mocks base method.
func (m *MockCarpoolRepo) CountPassengers(ctx context.Context, carpoolID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPassengers", ctx, carpoolID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPassengers indicates an expected call of CountPassengers.
func (mr *MockCarpoolRepoMockRecorder) CountPassengers(ctx, carpoolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPassengers", reflect.TypeOf((*MockCarpoolRepo)(nil).CountPassengers), ctx, carpoolID)
}

// Create mocks base method.
func (m *MockCarpoolRepo) Create(ctx context.Context, eventID, driverID uuid.UUID, req model.CreateCarpoolRequest) (model.Carpool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, driverID, req)
	ret0, _ := ret[0].(model.Carpool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCarpoolRepoMockRecorder) Create(ctx, eventID, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCarpoolRepo)(nil).Create), ctx, eventID, driverID, req)
}

// GetByID mocks base method.
func (m *MockCarpoolRepo) GetByID(ctx context.Context, id uuid.UUID) (model.Carpool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Carpool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCarpoolRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCarpoolRepo)(nil).GetByID), ctx, id)
}

// IsPassenger mocks base method.
func (m *MockCarpoolRepo) IsPassenger(ctx context.Context, carpoolID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPassenger", ctx, carpoolID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPassenger indicates an expected call of IsPassenger.
func (mr *MockCarpoolRepoMockRecorder) IsPassenger(ctx, carpoolID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPassenger", reflect.TypeOf((*MockCarpoolRepo)(nil).IsPassenger), ctx, carpoolID, userID)
}

// ListByEvent mocks base method.
func (m *MockCarpoolRepo) ListByEvent(ctx context.Context, eventID uuid.UUID) ([]model.Carpool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", ctx, eventID)
	ret0, _ := ret[0].([]model.Carpool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockCarpoolRepoMockRecorder) ListByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockCarpoolRepo)(nil).ListByEvent), ctx, eventID)
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// IsConfirmedParticipant mocks base method.
func (m *MockEventRepo) IsConfirmedParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmedParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmedParticipant indicates an expected call of IsConfirmedParticipant.
func (mr *MockEventRepoMockRecorder) IsConfirmedParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmedParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsConfirmedParticipant), ctx, eventID, userID)
}

// IsParticipant mocks base method.
func (m *MockEventRepo) IsParticipant(ctx context.Context, eventID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParticipant", ctx, eventID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsParticipant indicates an expected call of IsParticipant.
func (mr *MockEventRepoMockRecorder) IsParticipant(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParticipant", reflect.TypeOf((*MockEventRepo)(nil).IsParticipant), ctx, eventID, userID)
}
